const tongue_twisters = [
    "She dreamed &bull; of cheap ship trips &bull; on a chartered ship &bull; on the seven seas.",
    "A gnawing noise &bull; annoyed &bull; the nervous oyster.",
    "Lloyd spilled &bull; lemon liniment &bull; on the yellow linoleum.",
    "A skunk sat &bull; on a sycamore stump &bull; and stunk up &bull; the stump.",
    "Blake bought &bull; a black-backed bath brush &bull; in Blair's Bath Boutique.",
    "Daniel &bull; will hand you &bull; an annual &bull; cocker spaniel manual.",
    "The Swiss wristwatch shop &bull; shut soon &bull; after seven.",
    "Shirly sells &bull; preshrunk shirts &bull; at the sweatshirt shop.",
    "Neither &bull; of Ned's nieces' knees &bull; was knobby &bull; but Nellie's nephew's &bull; were.",
    "The minister's &bull; sinister &bull; moustache &bull; frustrated most sincere parishioners.",
    "The short-sleeved shirt &bull; should wash &bull; with the shorts &bull; and sheets &bull; in the wash.",
    "Phone friendly Fred &bull; at his toll-free number &bull; for fresh fried fish &bull; for Friday",
    "Sheep shouldn't sleep &bull; in chick shacks &bull; they should sleep &bull; in the sheep shacks.",
    "There's no biz &bull; like show biz &bull; on a no-show &bull; slow &bull; biz quiz show.",
    "Cheryl &bull; should choose &bull; new shoes &bull; her dog shouldn't choose &bull; to chew.",
    "The burger bun &bull; is buttered better &bull; because Betty bought &bull; better butter.",
    "The flea and the fly &bull; who flew in the flue &bull; got stuck &bull; in some super glue goo.",
    "Linda looked &bull; for lots of literary literature &bull; at the local library."
];